name: automerge
on:
  pull_request:
    types:
      - labeled
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
       
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.TRIGGER_ACCESS_TOKEN }}"
#          MERGE_LABELS: "automerge"
#          MERGE_RETRY_SLEEP: 5000
#          MERGE_RETRIES: 10
#          MERGE_FILTER_AUTHOR: "my-git-author"