name: Deploy
on:
 repository_dispatch:
  type:
    - type_of_event
  
jobs:
  build:
    runs-on: ubuntu-latest

    env:
        AZURE_CLENT_ID: ${{github.event.client_payload.azure_client_id}}
        
    steps:
      - name: build web
        run: |
          echo "build web app"
           echo "${INPUT_WORKFLOW_FILE_NAME}"
      - name: Send greeting
        run: echo "$AZURE_CLENT_ID"
          
      

    #ref: release-branch
    #wait_interval: 10
    #inputs: '{}'
    #propagate_failure: false
    #trigger_workflow: true
    #wait_workflow: true
