name: Deploy
on:
 repository_dispatch:
  type:
    - type_of_event
  
jobs:
  build:
    name: run and b
    runs-on: ubuntu-latest
    steps:
      - name: build web
        run: |
          echo "build web app"
           echo "${INPUT_WORKFLOW_FILE_NAME}"
      - name: Send greeting
        run: echo "${{ github.event.inputs.vn }}"
          
      

    #ref: release-branch
    #wait_interval: 10
    #inputs: '{}'
    #propagate_failure: false
    #trigger_workflow: true
    #wait_workflow: true
