name: Deploy
on:
  pull_request:
    
jobs:
  build:
    name: run and b
    runs-on: ubuntu-latest
    steps:
      - name: build web
        run: |
          echo "build web app"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
         owner: hariom
         repo: spring-boot-service-01
         github_token: ${{ secrets.TIGGER_ACCESS_TOKEN }}
    #github_user: github-user
         workflow_file_name: pr.yaml
         ref: feature/cicd
      - name: deploye
        run: |
          echo "deploy  web app"
          sleep 10s

    #ref: release-branch
    #wait_interval: 10
    #inputs: '{}'
    #propagate_failure: false
    #trigger_workflow: true
    #wait_workflow: true
     