name: Deploy
on:
 repository_dispatch:
  type:
    - Create Container
  
jobs:
  build:
    runs-on: ubuntu-latest

    env:
        ARM_CLIENT_ID: ${{github.event.client_payload.azure_client_id}}
        ARM_CLIENT_SECRET: ${{github.event.client_payload.azure_pass}}   
        ARM_TENANT_ID: ${{github.event.client_payload.azure_tenant_id}}      
        RSG_NAME: ${{github.event.client_payload.rsg_name}}              
        ACI_NAME: ${{github.event.client_payload.container_name}}           
        ACI_PORT:  ${{github.event.client_payload.aci_port}}    
        IMAGE:     ${{github.event.client_payload.docker_image_name}}     



    steps:
      - name: build web
        run: |
          echo "build web app"
           echo "${INPUT_WORKFLOW_FILE_NAME}"
      - name: Send greeting
        run: echo "$AZURE_CLENT_ID"

      - name: AZ Login
        run: 
          az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID

      - name: Deploy Image on Azure Container
        run: 
             az container create --resource-group $RSG_NAME --name $ACI_NAME --$IMAGE --$ACI_PORT
 
          
      

    #ref: release-branch
    #wait_interval: 10
    #inputs: '{}'
    #propagate_failure: false
    #trigger_workflow: true
    #wait_workflow: true
