name: Deploy
on:
 repository_dispatch:
  type:
    - create_container
  
jobs:
  build:
    runs-on: ubuntu-latest

    env:
        ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
        ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
        ARM_SUBSCRIPTION_ID: ${{secrets.AZ_SANDBOX_SPN_SUBSCRIPTION_ID}}
        ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
        RSG_NAME: sandbox          
        ACI_NAME: az-sandbox-container           
        ACI_PORT:  8080
        IMAGE:     ${{github.event.client_payload.docker_image_name}}     



    steps:
      - name: build web
        run: |
          echo "build web app"
           echo "${INPUT_WORKFLOW_FILE_NAME}"
      - name: Send greeting
        run: echo "$AZURE_CLENT_ID"

      - name: AZ Login
        run: 
          az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
          

      - name: Deploy Image on Azure Container
        run: 
             az container create --resource-group $RSG_NAME --name $ACI_NAME --$IMAGE --$ACI_PORT
 
          
      

    #ref: release-branch
    #wait_interval: 10
    #inputs: '{}'
    #propagate_failure: false
    #trigger_workflow: true
    #wait_workflow: true
