name: Deploy
on:
 workflow_dispatch:
  pull_request
    
jobs:
  build:
    name: run and b
    runs-on: ubuntu-latest
    steps:
      - name: build web
        run: |
          echo "build web app"
          
      

    #ref: release-branch
    #wait_interval: 10
    #inputs: '{}'
    #propagate_failure: false
    #trigger_workflow: true
    #wait_workflow: true
     